name: My Workflow

on:
  push:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
  workflow_dispatch:

jobs:
  lint_and_check:
    name: Check Syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Check Syntax Action
        uses: korkin25/action-syntax-check@main
